<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_model');
    } 

    /*
     * Listing of companies
     */
    function index()
    {
        $data['companies'] = $this->Company_model->get_all_companies();
        
        $data['_view'] = 'company/index';
        $this->load->view('layouts/main',$data);
    } 

    /*
     * Deleting company
     */
    function remove($company_id)
    {
        $company = $this->Company_model->get_company($company_id);

        // check if the company exists before trying to delete it
        if(isset($company['company_id']))
        {
            $this->Company_model->delete_company($company_id);
            redirect('company/index');
        }
        else
            show_error('The company you are trying to delete does not exist.');
    }
    
}
